# Generated by Django 5.2.5 on 2025-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image_delete_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('B', 'Boy')], default='C', max_length=3),
        ),
    ]
