# Generated by Django 5.2.5 on 2025-09-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_image_caption_alter_image_image_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('B', 'Boy'), ('G', 'Girl')], default='C', max_length=3),
        ),
    ]
